### PR TITLE
Dockerize nycoin

### PR DESCRIPTION
**Pull request by jmsds**
The goal to this PR is to automate the tasks involved for downloading the necessary dependencies, and building the binary. Instructions provided in the README.

### CODE REVIEW

**Review by cmelion — COMMENTED** [review]
Thanks for doing this.
One question, where did the IP addreses come from for addnode?

**Comment by cmelion** [comment]
@jmsds Also not sure if anyone with write/merge access is monitoring this repo, if you switch to https://github.com/NewYorkCoin-NYC/nycoin there is an active team there that will be happy to integrate the docker integration.

**Comment by jmsds** [comment]
@cmelion:

> One question, where did the IP addreses come from for addnode?


These nodes were copied from http://nycoin.net/, under **Windows Core Wallet Configuration**

**Comment by jmsds** [comment]
As @cmelion mentioned above, I'll move this over to the new repository. Thanks!

**Pull request closed without merging**
